name: HAP
version: "1.53"
license: "GPL-2.0-or-later"
date: 2023-02-27
description: |
    Homological Algebra Programming

authors:
    - name: Graham Ellis
      url: https://www.nuigalway.ie/our-research/people/mathematics-statistics-and-applied-mathematics/grahamellis/

maintainers:
    - name: Graham Ellis
      url: https://www.nuigalway.ie/our-research/people/mathematics-statistics-and-applied-mathematics/grahamellis/

GAP: ">= 4.5.6"

needed-pkgs:
    - name: "polycyclic"
      version: ">=1.1"
      url: "https://gap-packages.github.io/polycyclic/"
    - name: "crystcat"
      version: ">=1.1"
      url: "https://www.math.uni-bielefeld.de/~gaehler/gap/packages.php"
    - name: "fga"
      version: ">=1.1"
      url: "http://www.icm.tu-bs.de/ag_algebra/software/FGA/"
    - name: "aclib"
      version: ">=1.1"
      url: "https://gap-packages.github.io/aclib/"
    - name: "nq"
      version: ">=1.1"
      url: "https://gap-packages.github.io/nq/"

suggested-pkgs:
    - name: "gapdoc"
      version: ">=0.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "homology"
      version: ">=0.0"
    - name: "edim"
      version: ">=1.2.2"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/EDIM"
    - name: "singular"
      version: ">=06.07.23"
      url: "https://gap-packages.github.io/singular/"
    - name: "congruence"
      version: ">=0,0"
      url: "https://gap-packages.github.io/congruence"
    - name: "HAPcryst"
      version: ">=0.0.0"
      url: "https://gap-packages.github.io/hapcryst/"
    - name: "Polymaking"
      version: ">=0.8.3"
      url: "https://gap-packages.github.io/polymaking/"
    - name: "xmod"
      version: ">0.0"
      url: "https://gap-packages.github.io/xmod/"
    - name: "laguna"
      version: ">0.0"
      url: "https://gap-packages.github.io/laguna"

www: https://gap-packages.github.io/hap
readme: README.md
packageinfo: https://gap-packages.github.io/hap/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/hap/releases/download/v1.53/hap-1.53.tar.gz

abstract: |
    This package provides some functions for group cohomology and algebraic topology. 

status: accepted
doc-html: www/index.html
doc-pdf: doc/manual.pdf
keywords: |
    homology, cohomology, resolution, homotopy group, module of identities, CW complex, simplicial complex, cubical complex, permutahedral complex, knots, nonabelian tensor, nonabelian exterior, covering space.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Ell23</span>]   <b class='BibAuthor'>Ellis, G.</b>,
     <i class='BibTitle'>HAP, Homological Algebra Programming,
             Version 1.53</i>
     (<span class='BibYear'>2023</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/hap">https://gap-packages.github.io/hap</a></span>.
    </p>
    

bibtex: |
    @misc{ HAP1.53,
      author =           {Ellis, G.},
      title =            {{HAP}, Homological Algebra Programming, {V}ersion 1.53},
      month =            {Feb},
      year =             {2023},
      note =             {Refereed GAP package},
      howpublished =     {\href             {https://gap-packages.github.io/hap}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{hap}}},
      keywords =         {homology;   cohomology;  resolution;  homotopy  group;
                          module  of identities; CW complex; simplicial complex;
                          cubical   complex;   permutahedral   complex;   knots;
                          nonabelian tensor; nonabelian exterior; covering space},
      printedkey =       {Ell23}
    }

