DeclareGlobalFunction("CohomologyHomomorphism");
DeclareGlobalFunction("ConnectingCohomologyHomomorphism");
DeclareOperation("Sq",[IsAlgebra,IsInt,IsObject]);
DeclareGlobalFunction("HAP_coho_isoms");
DeclareGlobalFunction("ModPSteenrodAlgebra");
DeclareAttribute("HAP_MultiplicativeGenerators",IsAlgebra);
DeclareOperation("Bockstein",[IsAlgebra,IsObject]);
DeclareGlobalFunction("BocksteinHomology");
DeclareGlobalFunction("PrintAlgebraWordAsPolynomial");
