#!/bin/bash


file=$1;

if [ $# == 2 ]   
then
  opt1=$2;
  polymake "my \$c=load(\"$file\");  print \"$opt1\n\", \$c->$opt1, \"\n\n\";" ;
fi

if [ $# == 3 ]
then
  opt1=$2;
  opt2=$3;
  polymake "my \$c=load(\"$file\");  print \"$opt1\n\", \$c->$opt1, \"\n\n\", \"$opt2\n\", \$c->$opt2,  \"\n\n\";" ;
fi

if [ $# == 4 ]
then
  opt1=$2;
  opt2=$3;
  opt3=$4;
  polymake "my \$c=load(\"$file\");  print \"$opt1\n\", \$c->$opt1, \"\n\n\", \"$opt2\n\", \$c->$opt2,  \"\n\n\", \"$opt3\n\", \$c->$opt3, \"\n\n\" ;"
fi

