DeclareFilter("IsQuadraticNF");
DeclareProperty("QuadraticNF",IsQuadraticNF);
DeclareFilter("IsRingOfQuadraticIntegers");
DeclareProperty("RingOfQuadraticIntegers",IsRingOfQuadraticIntegers);
DeclareAttribute("AssociatedNumberField",IsNumberField);
DeclareAttribute("AssociatedRing",IsRing);
DeclareGlobalFunction("QuadraticNumberField");
DeclareOperation("RingOfIntegers",[IsNumberField]);
DeclareOperation("PrincipalIdeal",[IsRing and IsRingOfQuadraticIntegers, IsObject]);
DeclareFilter("IsPrincipalIdeal");
DeclareAttribute("PrincipalIdeal",IsPrincipalIdeal);
