DeclareFilter("IsQuadraticNF");
DeclareAttribute("QuadraticNF",IsQuadraticNF);
DeclareFilter("IsRingOfQuadraticIntegers");
DeclareAttribute("RingOfQuadraticIntegers",IsRingOfQuadraticIntegers);
DeclareFilter("HasAssociatedNF");
DeclareAttribute("AssociatedNumberField",HasAssociatedNF);
DeclareFilter("HasAssociatedRing");
DeclareAttribute("AssociatedRing",HasAssociatedRing);
DeclareGlobalFunction("QuadraticNumberField");
DeclareOperation("RingOfIntegers",[IsNumberField]);
DeclareOperation("PrincipalIdeal",[IsRing and IsRingOfQuadraticIntegers, IsObject]);
DeclareFilter("IsPrincipalIdeal");
DeclareAttribute("PrincipalIdeal",IsPrincipalIdeal);
