size(0,200);
defaultpen(0.2);
pen colour=blue+opacity(0.50);
real S=3.230;
path g=(-0.5,-S)--(0.5,-S)--(0.5,S)--(-0.5,S)--cycle;
picture fd;
real r=sqrt(1.);
pair z=(1.,0.);
path c=circle(z,r);
fill(fd,c,colour);draw(fd,c);
real r=sqrt(1.);
pair z=(-1.,0.);
path c=circle(z,r);
fill(fd,c,colour);draw(fd,c);
real r=sqrt(1.);
pair z=(0.,0.);
path c=circle(z,r);
fill(fd,c,colour);draw(fd,c);
real r=sqrt(1.);
pair z=(1.5,6.461);
path c=circle(z,r);
fill(fd,c,colour);draw(fd,c);
real r=sqrt(1.);
pair z=(-0.5,6.461);
path c=circle(z,r);
fill(fd,c,colour);draw(fd,c);
real r=sqrt(1.);
pair z=(0.5,6.461);
path c=circle(z,r);
fill(fd,c,colour);draw(fd,c);
real r=sqrt(1.);
pair z=(-1.5,6.461);
path c=circle(z,r);
fill(fd,c,colour);draw(fd,c);
draw(fd,g,white+linewidth(.3));
add(fd);
